# Generated by Django 3.2.9 on 2021-12-06 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dish', '0002_alter_dish_resturant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='saved_by',
            field=models.ManyToManyField(related_name='dishes_saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
