# Generated by Django 3.2.9 on 2021-12-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0003_resturant_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resturant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='resturant',
            name='longitude',
        ),
    ]
