# Generated by Django 3.2.9 on 2021-12-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0004_auto_20211206_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
